site_name: DaCデモ用
site_description: 戦略的ドキュメント管理システム

theme:
  name: material
  icon:
    logo: material/file-document-edit
  language: ja
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.share
    - content.tabs.link  # タブの連動
    - content.tooltips   # ツールチップ
    - content.code.copy  # ← これを追加するだけでコピーボタンが出現
    - content.code.annotate # ついでに注釈機能も入れる
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition          # 警告・注釈
  - pymdownx.details    # 折りたたみ表示
  - pymdownx.superfences: # Mermaid図面用
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - abbr
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true 
copyright: Copyright &copy; 2027 HamaRex-Development


nav:
  - ホーム: index.md
  - 規定:
    - A規定: kitei/a.md
  - 経営戦略:
    - IT投資ロードマップ: strategy/roadmap.md
    - 課題と解決策: strategy/pain_points.md
  - 技術ガバナンス:
    - 開発標準: tech/standards.md
    - セキュリティ規定: tech/security.md
  - 運用プロセス:
    - 更新フロー: operation/workflow.md
